FROM alpine-jdk:base
MAINTAINER javaonfly
COPY files/fxrate-configserver-0.0.1-SNAPSHOT.jar /opt/lib/
RUN mkdir /var/lib/config-repo
COPY config-repo /var/lib/config-repo
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/fxrate-configserver-0.0.1-SNAPSHOT.jar"]
VOLUME /var/lib/config-repo
EXPOSE 9090